name: flutter_google_auth_demo
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  firebase_auth: ^5.3.1
  google_sign_in: ^6.3.0
  firebase_ui_auth: ^2.0.0
  firebase_ui_oauth_google: ^1.4.3

flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0