import 'dart:convert';
import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/widgets.dart';

// IMPORTANT: You need to have your firebase_options.dart file generated by FlutterFire
import '../lib/firebase_options.dart';

// To run this script:
// 1. Make sure your flutter app is configured for Firebase (firebase_options.dart exists)
// 2. Run from the root of your project: dart run scripts/upload_data.dart
void main() async {
  // Boilerplate to initialize Firebase
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  print('Firebase Initialized.');

  final firestore = FirebaseFirestore.instance;
  final collection = firestore.collection('cars');

  // Path to your JSON file
  final file = File('assets/Dataset.json');
  final content = await file.readAsString();
  final List<dynamic> data = json.decode(content);

  print('Starting data upload to Firestore...');
  int count = 0;

  for (final carData in data) {
    // The JSON has string-encoded lists, so we need to parse them.
    List<String> parseList(String jsonString) {
      final decoded = json.decode(jsonString);
      return List<String>.from(decoded);
    }
    List<int> parseIntList(String jsonString) {
      final decoded = json.decode(jsonString);
      return List<int>.from(decoded);
    }

    // Create a structured document
    final carDocument = {
      'brand': carData['Brand'],
      'model': carData['Model'],
      'year': carData['Year'],
      'engine': carData['Engine'],
      'issues': parseList(carData['Issues']),
      'severities': parseList(carData['Severities']),
      'estimatedCostsINR': parseIntList(carData['EstimatedCostsINR']),
    };

    // Use a combination of brand, model, and year as the document ID
    final docId = '${carData['Brand']}_${carData['Model']}_${carData['Year']}'.replaceAll(' ', '_');

    await collection.doc(docId).set(carDocument);
    count++;
    print('Uploaded: $docId');
  }

  print('✅ Successfully uploaded $count documents to the "cars" collection!');
}